### ISSUE TITLE
Estudar api do Spotify

### ISSUE THREAD

**Issue by ygortgaleno** [fga-eps-mds/2019.1-StreamUs-Backend#15]
**Descrição:**
Essa issue tem como finalidade estudar a api do spotify e alinhar o conhecimento com a equipe

**Comment by victorcmoura** [comment]
Link para a documentação da API: https://developer.spotify.com/documentation/web-api/reference-beta/
Talvez seja útil para melhorar o entendimento da ferramenta da qual vocês dependem.
