### ISSUE TITLE
Administrar música em uma playlist colaborativa

### ISSUE THREAD

**Issue by ygortgaleno** [fga-eps-mds/2019.1-StreamUs-Backend#17]
**Eu como** Usuário
**Desejo** administrar as músicas em uma playlist colaborativa
**Para que** seja possível escutar músicas de diversas pessoas presentes na sala

**Descrição:**
Essa issue tem como finalidade administrar as músicas dentro de uma playlist colaborativa

**Critérios de aceitação**
- Adicionar uma música
- Remover uma música

**Task**
- [ ] criar endpoint POST de música
- [ ] criar endpoint DELETE de música
- [ ] Teste unitário

**Comment by oliveiraMarcelo** [comment]
issue moved to frontend

**Comment by oliveiraMarcelo** [comment]
Issue moved to [fga-eps-mds/2019.1-StreamUs-Frontend #15](https://github.com/fga-eps-mds/2019.1-StreamUs-Frontend/issues/15) via [**ZenHub**](https://www.zenhub.com/)
