### ISSUE TITLE
Criar componente Criar Playlist

### ISSUE THREAD

**Issue by pdaniel37** [fga-eps-mds/2019.1-StreamUs-Backend#48]
@oliveiraMarcelo commented on [Fri Apr 19 2019](https://github.com/fga-eps-mds/2019.1-StreamUs-Frontend/issues/3)

**Eu como** usuário
**Desejo** criar uma playlist
**Para que** seja possível escutar música em grupo

**Descrição:**
Criar barra de pesquisa, onde seja possível procurar músicas e adiciona-las a uma playlist para que seja possível escutar músicas em grupo

**Critérios de aceitação**
- Adicionar música em uma playlist
- Buscar músicas
- obedecer paleta de cores

**Task**
- [x] Criar componente barra de pesquisa
- [x] Criar componente de listar músicas

**Comment by oliveiraMarcelo** [comment]
Issue moved to [fga-eps-mds/2019.1-StreamUs-Frontend #14](https://github.com/fga-eps-mds/2019.1-StreamUs-Frontend/issues/14) via [**ZenHub**](https://www.zenhub.com/)
